import { Kata } from '.';

describe(Kata.name, () => {
    const testCases = [
        ['', ''],
        ['AAAA', 'TTTT'],
        ['ATTGC', 'TAACG'],
        ['GTAT', 'CATA'],
        ['CATTCACGTCCCGCTTTTA', 'GTAAGTGCAGGGCGAAAAT'],
        ['TGTGATCGATATGTTCCT', 'ACACTAGCTATACAAGGA'],
        ['CTTGT', 'GAACA'],
        ['TCCCCTTTGACTG', 'AGGGGAAACTGAC'],
        ['CTCGTAT', 'GAGCATA'],
        ['CATTTAGC', 'GTAAATCG'],
        ['AAGTGACAGCGATAGT', 'TTCACTGTCGCTATCA'],
        ['AGTTAGGGCACCCGACGAT', 'TCAATCCCGTGGGCTGCTA'],
        ['TCCTGCATCACCTACTTCG', 'AGGACGTAGTGGATGAAGC'],
        ['ATAATGCGGGAGTCACAG', 'TATTACGCCCTCAGTGTC'],
        ['GGTTCCCGCTAT', 'CCAAGGGCGATA'],
        ['GCCCGCC', 'CGGGCGG'],
        ['AGCCCCTGGAAACAACGCGCGTATATTGA', 'TCGGGGACCTTTGTTGCGCGCATATAACT'],
        ['CCGGAGGATATTAG', 'GGCCTCCTATAATC'],
        ['ATAAGCGGGGC', 'TATTCGCCCCG'],
        ['CAGGATACGTGTAG', 'GTCCTATGCACATC'],
        ['ACGCATATGTAATGCTGCAATAGAAT', 'TGCGTATACATTACGACGTTATCTTA'],
        ['CAATC', 'GTTAG'],
        ['GTCAGACTGCTGATCCCATGTATTCATGC', 'CAGTCTGACGACTAGGGTACATAAGTACG'],
        ['CCATAGTGCTGACGGCAC', 'GGTATCACGACTGCCGTG'],
        ['GGTTTAAAAACTTCCCGCTTA', 'CCAAATTTTTGAAGGGCGAAT'],
        ['CCTCGGTTCGAGCCAGT', 'GGAGCCAAGCTCGGTCA'],
        ['ATTAAGGTAAGTGTATATGCGCGTAGT', 'TAATTCCATTCACATATACGCGCATCA'],
        ['GCGTCAGCAACACTGGTTTATATCGGT', 'CGCAGTCGTTGTGACCAAATATAGCCA'],
        ['ACCAGAGCACCTTGACACAATCACAG', 'TGGTCTCGTGGAACTGTGTTAGTGTC'],
        ['CACCGTTTCAGACT', 'GTGGCAAAGTCTGA'],
        ['CTTAGGATCG', 'GAATCCTAGC'],
        ['GTGTGCTTGATTTAATGTGACCACG', 'CACACGAACTAAATTACACTGGTGC'],
        ['TTTAACATAAGGAAAGCTA', 'AAATTGTATTCCTTTCGAT'],
        ['ACAGACAGGGCA', 'TGTCTGTCCCGT'],
        ['GAAGA', 'CTTCT'],
        ['AGGATCCGT', 'TCCTAGGCA'],
        ['TGCTATTAGACACACACTCGTATGCTT', 'ACGATAATCTGTGTGTGAGCATACGAA'],
        ['CTGTCAGCACGG', 'GACAGTCGTGCC'],
        ['GAGTACGGCTAA', 'CTCATGCCGATT'],
        ['CTAACGCGGTCGGGTGATTTG', 'GATTGCGCCAGCCCACTAAAC'],
        ['ATTGCTTAACAATAAGG', 'TAACGAATTGTTATTCC'],
        ['TGGGCTACTCGTACT', 'ACCCGATGAGCATGA'],
        ['GCGCGGCTC', 'CGCGCCGAG'],
        ['ATAGAAGAG', 'TATCTTCTC'],
    ];

    it.each(testCases)('given "%s" should return "%s"', (input, expected) => {
        expect(Kata.dnaStrand(input)).toEqual(expected);
    });
});
